### ISSUE TITLE
unmonitor sonarr script issue (and feature resquest)

### ISSUE THREAD

**Issue by CptChaz** [Casvt/Plex-scripts#10]
Hi there,

seem to be having an issue trying to run the unmonitor_downloaded_episodes.py script on 

**sonarr
Version
3.0.7.1477
Package Version
3.0.7.1477-ls141 by [linuxserver.io](https://linuxserver.io/)
Mono Version
5.20.1.34**

via container on unraid. 

ui errors out with the following:

**Script exited with code: 1
Testing will execute the script with the EventType set to Test, ensure your script handles this correctly**

![Screen Shot 2022-04-13 at 1 11 34 PM](https://user-images.githubusercontent.com/55520028/163244499-1d6378ef-3201-479d-85f7-edc29b923ae6.png)

The relevant log entries are:
**13:11:20.6|Error|unmonitor_downloaded_episodes.py|Traceback (most recent call last):
13:11:20.6|Error|unmonitor_downloaded_episodes.py|  File "/config/scripts/unmonitor_downloaded_episodes.py", line 19, in <module>
13:11:20.6|Error|unmonitor_downloaded_episodes.py|    import requests
13:11:20.6|Error|unmonitor_downloaded_episodes.py|ModuleNotFoundError: No module named 'requests'
13:11:20.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Script exited with code: 1**

Just to make sure i haven't missed anything, i've got the script located in the appdata folder mapped to /config/scripts/, and made executable with chmod +x. Only changes made were to the "setup section" - here's my data entry on the script:
<img width="1272" alt="Screen Shot 2022-04-13 at 1 26 40 PM" src="https://user-images.githubusercontent.com/55520028/163246382-5afcbbec-e40e-4c3b-86c9-0c1d403ae4f6.png">

Looks like a great script, hopefully there' an easy fix for it. Also worth noting, the sonarr custom script options have changed slightly and now say "on download" instead of "on import".

As a small question / feature request, is there an easy, more automated way to install python3 in these sonarr containers without having to do a manual install each time the container changes? Thanks in advance, happy to help troubleshoot this if you need anything!

**Comment by Casvt** [comment]
Okay the error is that you don't have "requests" python package installed, which the script needs. Please execute the following command in the terminal of the container where the script is run: `python3 -m pip install requests`.

Concerning the help (it's not a feature request because it's not dependend on my script, it's a problem with python not being installed upon container changes/updates): let's handle that AFTER we've fixed the error. One thing at the time, so let's first fix the error and then fix this.

**Comment by CptChaz** [comment]
> Okay the error is that you don't have "requests" python package installed
you nailed it. had to install pip, too. once i had those three things (python3, pip, requests) it tested fine during the setup. 

now, once i implemented the script and tested with actual downloads, it didn't unmonitor the episode(s), and made the following log entries:

`2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|Traceback (most recent call last):
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 175, in _new_conn
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    (self._dns_host, self.port), self.timeout, **extra_kw
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 72, in create_connection
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|socket.gaierror: [Errno -2] Name or service not known
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|During handling of the above exception, another exception occurred:
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|Traceback (most recent call last):
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 710, in urlopen
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    chunked=chunked,
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    conn.request(method, url, **httplib_request_kw)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 239, in request
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/lib/python3.6/http/client.py", line 1285, in request
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    self._send_request(method, url, body, headers, encode_chunked)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/lib/python3.6/http/client.py", line 1331, in _send_request
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    self.endheaders(body, encode_chunked=encode_chunked)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/lib/python3.6/http/client.py", line 1280, in endheaders
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    self._send_output(message_body, encode_chunked=encode_chunked)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/lib/python3.6/http/client.py", line 1046, in _send_output
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    self.send(msg)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/lib/python3.6/http/client.py", line 984, in send
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    self.connect()
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 205, in connect
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    conn = self._new_conn()
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 187, in _new_conn
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    self, "Failed to establish a new connection: %s" % e
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1542a8531048>: Failed to establish a new connection: [Errno -2] Name or service not known
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|During handling of the above exception, another exception occurred:
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|Traceback (most recent call last):
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 450, in send
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    timeout=timeout
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 786, in urlopen
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 592, in increment
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    raise MaxRetryError(_pool, url, error or ResponseError(cause))
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.1.121:8989/api/v3/episode/monitor?apikey=(removed) (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1542a8531048>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|During handling of the above exception, another exception occurred:
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|Traceback (most recent call last):
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/config/scripts/unmonitor_downloaded_episodes.py", line 30, in <module>
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    requests.put('http://' + sonarr_ip + ':' + sonarr_port + '/api/v3/episode/monitor?apikey=(removed) + sonarr_api_token, json={'episodeIds':[sonarr_episodefile_episodeids],'monitored':'false'})
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 132, in put
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    return request('put', url, data=data, **kwargs)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    return session.request(method=method, url=url, **kwargs)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 529, in request
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    resp = self.send(prep, **send_kwargs)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 645, in send
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    r = adapter.send(request, **kwargs)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 519, in send
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|    raise ConnectionError(e, request=request)
2022-04-14 11:41:42.3|Error|unmonitor_downloaded_episodes.py|requests.exceptions.ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.1.121:8989/api/v3/episode/monitor?apikey=(removed) (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1542a8531048>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

something on my end?

**Comment by Casvt** [comment]
The value of the variable sonarr_ip should be `192.168.1.212`, not `http://192.168.1.121`.

**Comment by CptChaz** [comment]
To your credit, this was originally how i set up the script (not including http://) however, i added that when i was troubleshooting before posting my issue, and forgot to remove it afterwards.

Now that we've got that fire put out, log entries are much shorter so hopefully we're honing it in. Episodes still aren't being unmonitored, so i enabled debugging. Here's the relevant log entry for my most recent download/import:

`2022-04-14 17:00:58.6|Debug|CustomScript|Executing external script: /config/scripts/unmonitor_downloaded_episodes.py
2022-04-14 17:00:58.6|Debug|unmonitor_downloaded_episodes.py|Starting /config/scripts/unmonitor_downloaded_episodes.py 
2022-04-14 17:00:58.8|Debug|Api|[PUT] /api/v3/episode/monitor?apikey=(removed) 303.SeeOther (0 ms)
2022-04-14 17:00:58.8|Debug|Api|[GET] /api/v3/episode/monitor?apikey=(removed) 404.NotFound (0 ms)
2022-04-14 17:00:58.8|Debug|CustomScript|Executed external script: /config/scripts/unmonitor_downloaded_episodes.py - Status: 0
2022-04-14 17:00:58.8|Debug|CustomScript|Script Output: 

2022-04-14 17:00:58.9|Debug|CompletedDownloadService|All episodes were imported for ...`

Thanks again for helping with this.

**Comment by Casvt** [comment]
Alright this is a more interesting problem.

1. Do you have Sonarr V3? And not V2?
2. Do you have a "URL Base" setup in Sonarr (Settings -> General)? If so, append it to the sonarr_ip var like this: `[ip]/[url_base]`

**Comment by Casvt** [comment]
I've updated the README to better instruct people on how to setup the scripts (most importantly the variables).

**Comment by CptChaz** [comment]
> I've updated the README to better instruct people on how to setup the scripts (most importantly the variables).

nice!

> 1. Do you have Sonarr V3? And not V2?

V3
> 2. Do you have a "URL Base" setup in Sonarr (Settings -> General)? If so, append it to the sonarr_ip var like this: `[ip]/[url_base]`

yep, it's reverse proxied, so i appended with url base. made the log entry even shorter this time, almost too short...

2022-04-15 08:41:15.5|Debug|CustomScript|Executing external script: /config/scripts/unmonitor_downloaded_episodes.py
2022-04-15 08:41:15.5|Debug|unmonitor_downloaded_episodes.py|Starting /config/scripts/unmonitor_downloaded_episodes.py 
2022-04-15 08:41:15.9|Debug|CustomScript|Executed external script: /config/scripts/unmonitor_downloaded_episodes.py - Status: 0
2022-04-15 08:41:15.9|Debug|CustomScript|Script Output: 

2022-04-15 08:41:15.9|Debug|HistoryService|Trying to find downloadId for [redacted].mp4 from history
2022-04-15 08:41:16.0|Debug|HistoryService|Trying to find downloadId for [redacted].mp4 from history...


confirmed on 2 episodes, not being unmonitored. really strange.

**Comment by Casvt** [comment]
The script is working now. Sonarr isn't. I know the script is working because it exited with code 0 which is good. And after the script was executed, you can see that Sonarr is searching in it's database for the episode so that it can unmonitor it.

The script has asked Sonarr to unmonitor the episode with id XYZ, so Sonarr starts searching for that id in its history logs to find the corresponding episode to unmonitor: 

> 2022-04-15 08:41:15.9|Debug|HistoryService|Trying to find downloadId for [redacted].mp4 from history

It seems like Sonarr can't find it. Like Sonarr can't find the episode.

-----------

Basically, when we ask Sonarr to unmonitor something, it can't. That would mean that it also wouldn't work when you click the unmonitor button of an episode from the web-ui. When you click the unmonitor button in the web-ui, the exact same request to Sonarr is made that my script makes. When my script makes it, Sonarr can't do it, so when the web-ui asks it, it also shouldnt work:

Can you try to unmonitor the episode manually from the web-ui?

This is outside of my script (my script is working after all) and more a Sonarr problem. I'll help you of course, but if it really starts to get deep into Sonarr, I'll let you know to start a thread on the Sonarr forums as there are smarter people there, specialized in Sonarr. You can always link this issue in the thread for extra context. 

But for now let's troubleshoot together.

**Comment by Casvt** [comment]
Well yes this does indeed mean something to me.

> I believe this should be 192.168.1.121:8989/sonarr so i made the change of adding the url base to the end of port for now like this sonarr_port = '8989/sonarr'

You are completely right. I've edited the README to fix this because you are right that it should be appended to the port and not the ip. I'm so sorry haha

> Request Failed. PUT /api/v3/episode/monitor: Could not convert string to integer: None. Path 'episodeIds[0]', line 1, position 22. (Json snippet 'episodeIds": ["None"<--error-->], "monitored": "fal')

What this basically suggests is that my script said to sonarr: "Hey can you unmonitor the script with the id of 'None' ?" Well that's of course not going to work because no episode has the id of "None". I know what the problem is, so I'll get back to you when I've found the solution.

**Comment by Casvt** [comment]
Alright.

I've made some changes to the file (and uploaded those to GitHub), but these shouldn't matter for you. But still, download the new version of the script and use that one from now on just to make sure.

---

I've tried the script myself (entered variables, added it to sonarr and downloaded an episode) and it worked fine. I've found where to problem _should_ be for you and how we can find it to confirm it. What I mean with that is that I know where the problem should be, and that even though I don't have a problem there, you probably will as that is where it is going wrong.

Do the following please:
1. In the sonarr web-ui, go to Settings -> General -> Logging -> Log Level and set it to Trace (and click save)
2. Download an episode with the (new version of the) script setup
3. After it is done downloading and the script is run, go to System -> Log Files -> `sonarr.trace.txt` -> Download, and share the content (it should be quite big but that's fine)
4. Go to Settings -> General -> Logging -> Log Level and set it back to Info  (and click save)

As said, please share the content of the `sonarr.trace.txt` file. There is some sensitive info in there, so share it here, I'll take a quick look at it to find what I'm looking for and will then delete your comment so that the info is "lost" ("lost" intentionally; for safety purposes).

Tip:
Doing \`code\` to share code is good if the code is _one line_ (e.g. find the file called `sonarr.trace.txt`).

If you have _multiple lines_ of code (e.g. outputs of logs), do the following  instead and see the difference. It's much easier to read for me and anyone else.
\`\`\`
log line 1
log line 2
\`\`\`
instead of
\`
log line 1
log line 2
\`
Result:
```
log line 1
log line 2
```
instead of
`
log line 1
log line 2
`

**Comment by mynvnow** [comment]
Slight offtopic, can the unmonitor script be done in python 2.7 without additional packages or as bash script? linuxserver sonarr image comes with 2.7 and resets on every update.

**Comment by Casvt** [comment]
> Slight offtopic, can the unmonitor script be done in python 2.7 without additional packages or as bash script? linuxserver sonarr image comes with 2.7 and resets on every update.

I think it will work in 2.7, but the requests module is still needed. Even if it was written as bash script, it would need the curl package so either way the script needs a dependency.

The problem with the image resetting upon update is an issue that you need to present to linuxserver.io and not to me. (To say it in a mean way...) Go to their forums and present your problem there and not to me; I'm not the creator of those images so it's not my responsibility to fix issues like these. BTW, @CptChaz also uses linuxserver images and has the same problem with them resetting upon update. So go to their forums [here](https://discourse.linuxserver.io/) and present your issue there. Again sorry for saying it in a such a mean way but really no other way to get the point over.

**Comment by mynvnow** [comment]
You're good. Thanks for the reply. I will go to linuxserver forums.

**Comment by CptChaz** [comment]
@mynvnow i will gladly chime in if you post a thread link here.

@Casvt you fixed the script, it works exactly as it should for me, now! thank you so much for your time here. i'm very much appreciative. 

if i were to just put together a simple little bash script to install the script dependancies and set the trigger on "application update" do you think that would be a good solution?

**Comment by Casvt** [comment]
> you fixed the script

Oh wow so the little fix that wasn't supposed to do anything, did it. And yet the version before this "fix" already worked for me but not for you. Weird... but I don't care haha it's working now.

> if i were to just put together a simple little bash script to install the script dependancies and set the trigger on "application update" do you think that would be a good solution?

Well yeah I do. Sounds like it should work. Images and containers are not my strong point but I can definitely help with other parts of the bash script (like installing the dependencies, downloading the script, filling the variables from "outside" using regex and sed, etc.).

---

To just recap:
1. You didn't have the requests module installed. The documentation inside the scripts are all slowly updated to help with this.
2. You gave the variables the wrong values and didn't know where to put the url prefix. The README has been updated to help with this.
3. There was a bug in the script that I couldn't recreate or even detect. It was fixed by chance haha. Literally nothing I could do about that one.

So I'd say that not only are all your problems solved, but future similar problems from other users are also avoided now by the improved documentation. So a pat on the shoulder for both of us eh?

**Comment by mynvnow** [comment]
I did not create a forum post yet @CptChaz you're free to create one if you want to. I fixed the problem by writing a python2 script without any dependencies (aka no need to install pip/requests). Image comes with preinstalled python2.7 so this should work fine. ✌️

https://gist.github.com/mynvnow/5d01d981650a7783c7f8bf743350a797

**Comment by Casvt** [comment]
Oh nice. Would this mean that the only thing not working now is that the script gets removed upon image update?

**Comment by mynvnow** [comment]
Script will not be removed if saved outside of the container. Script can be saved anywhere accessible by sonarr

**Comment by Casvt** [comment]
Yeah that's true. I'll let you two people figure it out and when you're done close this issue. Good to see everything working out

**Comment by mynvnow** [comment]
All good from my side. You can close if @CptChaz has nothing to add.

Btw, you can do a put request without requests package. Will save from an additional install and little space 😜
Ex: https://stackoverflow.com/questions/25491541/python3-json-post-request-without-requests-library

**Comment by Casvt** [comment]
> Btw, you can do a put request without requests package. Will save from an additional install and little space

For such a script where there is only one request made, it might be a good idea yeah. For larger scripts, requests becomes basically necessary if you want to have decent looking code. But for a script with one request being made, it's fine yeah. Maybe I'll re-write the script with urllib instead of requests.

**Comment by CptChaz** [comment]
> So a pat on the shoulder for both of us eh?

absolutely my friend. Thanks again for helping with this. Issue ready to close. 

Out of curiosity, are you interested in collaborating on another project with your scripts here? They would make great plugins for another project I’m involved with and your dev skills would be very welcome there.

**Comment by Casvt** [comment]
> Out of curiosity, are you interested in collaborating on another project with your scripts here? They would make great plugins for another project I’m involved with and your dev skills would be very welcome there.

Well yeah of course. Tell me about it!

**Comment by CptChaz** [comment]
Then this sounds like it’s right in your wheelhouse 

https://github.com/Unmanic/unmanic

We currently have a couple sonarr/radarr plugins in beta, as well as a multitude of other ffmpeg plugins, and is a good open source competitor of tdarr. Our discord community is very active and the creator dev is extremely active. Would love for you to pop in and see if it’s something you’re interested in! You can tag me @CptChaz or the creator @josh.5 if you pop in. 

https://unmanic.app/discord

**Comment by Josh5** [comment]
Hey @Casvt, Chaz tells me that you are working on some awesome things. From a quick look over your python scripts, I doubt they would take much modification to run from Unmanic.

If you are interested in collaborating on something opensource, come chat my friend. Hit me up on Discord.

**Comment by CptChaz** [comment]
i know this issue is closed, but for anyone that stumbles across this in the future, linuxserver.io has a way to automate the installation of dependancies like python3 here 
[https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers](url)
