### ISSUE TITLE
plex import export. Fails to import all intro markers

### ISSUE THREAD

**Issue by shaddowlink** [Casvt/Plex-scripts#183]
Hello, 
I tried serveral times now, my script will fail after a few minutes trying to import all intro markers. 
I get this error.

```
/opt/scripts$ sudo ./plex_exporter_importer.py -t import -a -p intro_marker -L plex_exporter_importer.db
Importing from plex_exporter_importer.db
You're going to import the following:
        The intro marker of episodes, which describes the beginning and end of t                                                                             he intro.
This is going to be done for your complete plex library.

3D Movies (SBS)
4K Movies
4K Movies (English only)
Movies
Movies (English only)
4K TV
4K TV (English only)
Animes
Shutting down...
Progress saved
AN ERROR OCCURED. ALL YOUR PROGRESS IS SAVED. PLEASE SHARE THE FOLLOWING WITH TH                                                                             E DEVELOPER:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scripts/./plex_exporter_importer.py", line 1426, in <module>
    response = plex_exporter_importer(
  File "/opt/scripts/./plex_exporter_importer.py", line 1359, in plex_exporter_importer
    _leave(**exit_args, e=e)
  File "/opt/scripts/./plex_exporter_importer.py", line 442, in _leave
    raise e
  File "/opt/scripts/./plex_exporter_importer.py", line 1268, in plex_exporter_importer
    episode_info = ssn.get(f'{base_url}/library/metadata/{show["ratingKey"]}/all                                                                             Leaves', params={'includeGuids': '1'}).json()['MediaContainer']['Metadata']
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by shaddowlink** [comment]
It seems they go partially imported, but not everything. I tried exporting them again from old libary and importing them again without success

**Comment by Casvt** [comment]
Can you run the script again with the `-v` flag added? It will show in more detail where it's going wrong.

The error suggests that at some point the server gives an unexpected response, like when media is not found or suddenly the token is invalid. When we see what media item it crashes on, we'll be able to see what is so special about the media item that it makes the script halt.

**Comment by shaddowlink** [comment]
This is whats comming before, just a list of the Season / episode the script is on. 
```
                S2E16 - Gortimer = Mel, Ranger = Catherine
                S2E17 - Mel und die Sache mit den Pferden
                S2E18 - Die größte Vorstellung des Raymond Bloodstone
                S2E19 - Ranger und die Last der Welt
                S2E20 - Die Beste Mom der Welt
                S2E21 - Mel und der verpasste Tag
                S2E22 - Die Abenteuer von White Hat & Gortimer
                S2E23 - Gortimer und die Legende der Normal Street
                S2E24 - Das Liebeselixier
                S2E25 - Gortimer und das Beben der Normal Street
                S2E26 - Gortimer, Mel & Ranger und die Zeitkapsel
        Gossip Girl
Shutting down...
Progress saved
AN ERROR OCCURED. ALL YOUR PROGRESS IS SAVED. PLEASE SHARE THE FOLLOWING WITH THE DEVELOPER:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scripts/./plex_exporter_importer.py", line 1426, in <module>
    response = plex_exporter_importer(
  File "/opt/scripts/./plex_exporter_importer.py", line 1359, in plex_exporter_importer
    _leave(**exit_args, e=e)
  File "/opt/scripts/./plex_exporter_importer.py", line 442, in _leave
    raise e
  File "/opt/scripts/./plex_exporter_importer.py", line 1244, in plex_exporter_importer
    show_info = ssn.get(f'{base_url}/library/metadata/{show["ratingKey"]}', params={'includePreferences': '1','includeGuids': '1'}).json()['MediaContainer']['Metadata'][0]
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
shaddowlink@sb:/opt/scripts$

```
running it again and againit showed that it broke at different points with excatly the same flags. On different shows, aswell as on different Libaries

**Comment by Casvt** [comment]
Probably some sort of rate limiting or timing out or database blocking happening at Plex for it to respond in such way at random requests. Run the script with less media at a time, like only a few libraries per run.
