### ISSUE TITLE
Postcredit scene notification

### ISSUE THREAD

**Issue by PierreDurrr** [Casvt/Plex-scripts#52]
Back in the days i was using Kodi, there was an extension that would display a popup if the movie as a postcredit or aftercredit scene : [https://forum.kodi.tv/showthread.php?tid=235217](https://forum.kodi.tv/showthread.php?tid=235217)

Maybe 2 notifications, at beginning of movie and à reminder just before endcredits start

Don't know if it could be made to Plex but that would be awesome !

**Comment by Casvt** [comment]
Your request has been completed. You can find the script here: https://github.com/Casvt/Plex-scripts/blob/main/various/postcreditscene_notification.py.

If you have any questions or requests, let me know. Enjoy! \:\)

**Comment by PierreDurrr** [comment]
Thanks !
However it doesn't to work. Both apprise docker-mod and tautulli are linuxserver's latest versions and apprise is confirmed to work as i tried it manually. also tried the script manually on another machine with apprise enabled and no notification received.
I can confirm my apprise address is ok.

Tautulli log below :
```
today at 11:03:252022-08-30 11:03:25 - DEBUG :: Thread-3 : Tautulli Notifiers :: Trying to run notify script: /00-scripts/postcreditscene_notification.py, arguments: ['--Title', 'Thor', '--Year', '2000'], action: play
today at 11:03:252022-08-30 11:03:25 - DEBUG :: Thread-3 : Tautulli Notifiers :: Full script is: ['/usr/bin/python3', '/00-scripts/postcreditscene_notification.py', '--Title', 'Thor', '--Year', '2000']
today at 11:03:252022-08-30 11:03:25 - DEBUG :: Thread-3 : Tautulli Notifiers :: Executing script in a new thread.
today at 11:03:262022-08-30 11:03:26 - DEBUG :: Thread-29 : Tautulli Notifiers :: Subprocess returned with status code 0.
today at 11:03:262022-08-30 11:03:26 - INFO :: Thread-29 : Tautulli Notifiers :: Script notification sent.
```

**Comment by Casvt** [comment]
It didn't find the movie in [aftercredits.com](aftercredits.com). If it finds the movie and there is an post credit scene, it will tell you in the tautulli logs. However, we don't see that while we know that Thor has a post credit scene.

So the webscraping didn't work correctly. I'll see if I can improve the webscraping part to better try to find a match from the search results. Will be home from school in 4 hours.

**Comment by Jerrk** [comment]
I gave this a try as well with the movie "iron man".

Sending a test notification to the apprise URL works as expected.

My tautulli logs:
<html><body>


2022-08-30 21:39:44 | INFO | Tautulli Notifiers :: Script notification sent.
-- | -- | --
2022-08-30 21:39:44 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 0.
2022-08-30 21:39:37 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2022-08-30 21:39:37 | DEBUG | Tautulli  Notifiers :: Full script is: ['/usr/local/bin/python',  '/config/scripts/postcreditscene_notification.py', '--Title', 'Iron  Man', '--Year', '2008']
2022-08-30 21:39:37 | DEBUG | Tautulli  Notifiers :: Trying to run notify script:  /config/scripts/postcreditscene_notification.py, arguments: ['--Title',  'Iron Man', '--Year', '2008'], action: play


</body>
</html>

**Comment by Casvt** [comment]
Yeah so the same thing. The webscraping part doesn't work well.

**Comment by PierreDurrr** [comment]
Also, after checking on aftercredits.com i tried to run _Minions 2_ as it is referenced to have after credits scene, could it be possible to perform a search on original title ? As a search with localized title doesn't seems to trigger the script.

**Comment by AfterCredits** [comment]
> Your request has been completed. You can find the script here: https://github.com/Casvt/Plex-scripts/blob/main/various/postcreditscene_notification.py.
> 
> If you have any questions or requests, let me know. Enjoy! :)

I applaud your effort and your ambition, but just a heads up, most people like to be asked permission if someone is going to be scrapping their website for info...

**Comment by Casvt** [comment]
@AfterCredits 
>I applaud your effort and your ambition, but just a heads up, most people like to be asked permission if someone is going to be scrapping their website for info...

That's fair. Sorry for that. In my defence though: the problem with people web scraping is that they put a big load on the server by making a lot of requests to a webserver that is intended for just the normal amount of requests being made by a standard user. This script makes exactly one request (which is even less than what a standard visitor to your website makes) and thus I didn't see it as a problem. It's not like I'm scraping every movie on your site at once or something like that. One request is all.

Again, I agree and I'm sorry for not asking but I didn't see it as a problem, looking at how not-intruding my script is to the web server.

**Comment by Casvt** [comment]
@PierreDurrr, @Jerrk 
Fixed the web scraping part. Please re-download the script.

**Comment by Casvt** [comment]
@PierreDurrr 
> Also, after checking on aftercredits.com i tried to run _Minions 2_ as it is referenced to have after credits scene, could it be possible to perform a search on original title ? As a search with localized title doesn't seems to trigger any result.

Do you mean the "Original Title" field of the media in Plex?

**Comment by PierreDurrr** [comment]
> @PierreDurrr
> 
> > Also, after checking on aftercredits.com i tried to run _Minions 2_ as it is referenced to have after credits scene, could it be possible to perform a search on original title ? As a search with localized title doesn't seems to trigger any result.
> 
> Do you mean the "Original Title" field of the media in Plex?

Yup, that one !

**Comment by PierreDurrr** [comment]
> @PierreDurrr script has been updated to now search for original title first. If it is not set, the title is used. Please redownload the script and take notice of the setup procedure because it has changed.

Thanks, it seems to be perfectly working now !
Will down a bit more testing and report

**Comment by dasauto1** [comment]
I seem to have run in to the same issue (latest script). This particular movie is on aftercredits (matrix 2021) but I dont seem to get any notification. I tried with discord and join from apprise. 

`

2022-10-06 14:09:17 | INFO | Tautulli Notifiers :: Script notification sent.
-- | -- | --
2022-10-06 14:09:17 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 0.
2022-10-06 14:09:15 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2022-10-06 14:09:15 | DEBUG | Tautulli  Notifiers :: Full script is: ['/opt/.venv/tautulli/bin/python3',  '/opt/tautulli/scripts/postcreditscene_notification.py', '--RatingKey',  '8494']
2022-10-06 14:09:15 | DEBUG | Tautulli  Notifiers :: Trying to run notify script:  /opt/tautulli/scripts/postcreditscene_notification.py, arguments:  ['--RatingKey', '8494'], action: play
2022-10-06 14:09:15 | INFO | Tautulli NotificationHandler :: Preparing notification for notifier_id 2.
2022-10-06 14:09:15 | DEBUG | Tautulli NotificationHandler :: Custom conditions evaluated to 'True'. Conditions: [True].
2022-10-06 14:09:15 | DEBUG | Tautulli NotificationHandler :: Condition logic [blank]: {1} > True

`

**Comment by dasauto1** [comment]
`Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/opt/tautulli/scripts/postcreditscene_notification.py", line 81, in <module>
            response = postcreditscene_notification(rating_key=args.RatingKey)
        File "/opt/tautulli/scripts/postcreditscene_notification.py", line 56, in postcreditscene_notification
            search_results = requests_get(f'https://aftercredits.com/', params={'s': f'{title} {year}'}, headers={'Host': 'aftercredits.com','Referer': f'https://aftercredits.com/?s={title}+{year}'.replace(' ','+'), 'sec-ch-ua': '"Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"'}).text
        File "/opt/tautulli/lib/requests/api.py", line 75, in get
            return request('get', url, params=params, **kwargs)
        File "/opt/tautulli/lib/requests/api.py", line 61, in request
            return session.request(method=method, url=url, **kwargs)
        File "/opt/tautulli/lib/requests/sessions.py", line 529, in request
            resp = self.send(prep, **send_kwargs)
        File "/opt/tautulli/lib/requests/sessions.py", line 645, in send
            r = adapter.send(request, **kwargs)
        File "/opt/tautulli/lib/requests/adapters.py", line 440, in send
            resp = conn.urlopen(
        File "/opt/tautulli/lib/urllib3/connectionpool.py", line 703, in urlopen
            httplib_response = self._make_request(
        File "/opt/tautulli/lib/urllib3/connectionpool.py", line 398, in _make_request
            conn.request(method, url, **httplib_request_kw)
        File "/opt/tautulli/lib/urllib3/connection.py", line 239, in request
            super(HTTPConnection, self).request(method, url, body=body, headers=headers)
        File "/usr/lib/python3.9/http/client.py", line 1255, in request
            self._send_request(method, url, body, headers, encode_chunked)
        File "/usr/lib/python3.9/http/client.py", line 1296, in _send_request
            self.putheader(hdr, value)
        File "/opt/tautulli/lib/urllib3/connection.py", line 224, in putheader
            _HTTPConnection.putheader(self, header, *values)
        File "/usr/lib/python3.9/http/client.py", line 1228, in putheader
            values[i] = one_value.encode('latin-1')
    UnicodeEncodeError: 'latin-1' codec can't encode characters in position 28-30: ordinal not in range(256) `

Here is the full error while playing non-english media. I checked with various files too. Thanks.

**Comment by Casvt** [comment]
@dasauto1 Character issue has been resolved so please redownload script. The problem with `, The` I'll resolve later.

**Comment by Casvt** [comment]
Alright never mind I've fixed the `, The` problem too already so everything is resolved now :)

**Comment by dasauto1** [comment]
Thanks for the fix, however seems to have run in to this error now after updating the script.


```
Tautulli Notifiers :: Script error:
    Traceback (most recent call last):
        File "/opt/tautulli/lib/urllib3/connection.py", line 174, in _new_conn
            conn = connection.create_connection(
        File "/opt/tautulli/lib/urllib3/util/connection.py", line 95, in create_connection
            raise err
        File "/opt/tautulli/lib/urllib3/util/connection.py", line 85, in create_connection
            sock.connect(sa)
    TimeoutError: [Errno 110] Connection timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
        File "/opt/tautulli/lib/urllib3/connectionpool.py", line 703, in urlopen
            httplib_response = self._make_request(
        File "/opt/tautulli/lib/urllib3/connectionpool.py", line 398, in _make_request
            conn.request(method, url, **httplib_request_kw)
        File "/opt/tautulli/lib/urllib3/connection.py", line 239, in request
            super(HTTPConnection, self).request(method, url, body=body, headers=headers)
        File "/usr/lib/python3.9/http/client.py", line 1255, in request
            self._send_request(method, url, body, headers, encode_chunked)
        File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
            self.endheaders(body, encode_chunked=encode_chunked)
        File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
            self._send_output(message_body, encode_chunked=encode_chunked)
        File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
            self.send(msg)
        File "/usr/lib/python3.9/http/client.py", line 950, in send
            self.connect()
        File "/opt/tautulli/lib/urllib3/connection.py", line 205, in connect
            conn = self._new_conn()
        File "/opt/tautulli/lib/urllib3/connection.py", line 186, in _new_conn
            raise NewConnectionError(
    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff554625340>: Failed to establish a new connection: [Errno 110] Connection timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
        File "/opt/tautulli/lib/requests/adapters.py", line 440, in send
            resp = conn.urlopen(
        File "/opt/tautulli/lib/urllib3/connectionpool.py", line 785, in urlopen
            retries = retries.increment(
        File "/opt/tautulli/lib/urllib3/util/retry.py", line 592, in increment
            raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='***.***.***.***', port=32400): Max retries exceeded with url: /library/metadata/8494?X-Plex-Token=**************** (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff554625340>: Failed to establish a new connection: [Errno 110] Connection timed out'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
        File "/opt/tautulli/scripts/postcreditscene_notification_new.py", line 91, in <module>
            response = postcreditscene_notification(rating_key=args.RatingKey)
        File "/opt/tautulli/scripts/postcreditscene_notification_new.py", line 52, in postcreditscene_notification
            media_info = requests_get(f'{base_url}/library/metadata/{rating_key}', params={'X-Plex-Token': plex_api_token}, headers={'Accept': 'application/json'}).json()['MediaContainer']['Metadata'][0]
        File "/opt/tautulli/lib/requests/api.py", line 75, in get
            return request('get', url, params=params, **kwargs)
        File "/opt/tautulli/lib/requests/api.py", line 61, in request
            return session.request(method=method, url=url, **kwargs)
        File "/opt/tautulli/lib/requests/sessions.py", line 529, in request
            resp = self.send(prep, **send_kwargs)
        File "/opt/tautulli/lib/requests/sessions.py", line 645, in send
            r = adapter.send(request, **kwargs)
        File "/opt/tautulli/lib/requests/adapters.py", line 519, in send
            raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='***.***.***.***', port=32400): Max retries exceeded with url: /library/metadata/8494?X-Plex-Token=**************** (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff554625340>: Failed to establish a new connection: [Errno 110] Connection timed out')) 
```
